### PR TITLE
Add new regions to Manifest::REGIONS

### PR DESCRIPTION
**Pull request by hamchapman**
As the title says, add the new regions to the valid regions list

### CODE REVIEW

**Comment by cdwort** [comment]
Hey @hamchapman Thanks for the PR.

I'm new to this codebase, but I'm struggling to see where this constant is actually used.

Can you briefly describe what you were seeing?

**Comment by hamchapman** [comment]
It's referenced here: https://github.com/heroku/kensa/blob/master/lib/heroku/kensa/check.rb#L114

And with the new regions being made available, they need to be added to the list as valid. That's the reason for the change.

**Comment by cdwort** [comment]
Hey @hamchapman Thanks! Sorry about that.. I just found it too myself.

**Comment by mathias** [comment]
Thanks @hamchapman !

**Comment by cdwort** [comment]
LGTM. Merging and I expect we'll cut a release this afternoon.

Thanks for this!

**Pull request merged**
