### PR TITLE
Remove term-ansicolor yellow; create new generic warning method

### LINKED ISSUE #97: Error: undefined method 'yellow'
I ran a command similar to this with Kensa 2.4.3:

```
kensa run -f addon-manifest.json -p myplan sh
```
And got this error:

```
Testing config data
  Check is a hash [PASS]
  Check all config keys were previously defined in the manifest [PASS]
  Check all keys in the manifest are present/home/andrew/.gem/ruby/2.0.0/gems/kensa-2.4.3/lib/heroku/kensa/check.rb:206:in `block in call!': undefined method `yellow' for #<Heroku::Kensa::ProvisionResponseCheck:0x007f76a5f5d3b8> (NoMethodError)
```

When I run the same command in Kensa 2.4.2, it works fine. I am completely new to Kensa so I'm far from sure that this is a regression, but it seemed worth flagging up here.

In particular, this change looks suspicious:

https://github.com/heroku/kensa/commit/87905ca1eb66d4e6739ee2a4af5660d4082437e5#diff-f66b8de549216f35e05b5c866024b854L171

### PR DESCRIPTION
**Pull request by mathias**
Fixes #97

### CODE REVIEW

**Comment by mathias** [comment]
@bjeanes This outputs a yellow warning, not a check failure. It seems OK that we don't specify the provision response to provide all config vars defined in the manifest, though, because we allow providers to set them after the provision. Does that sound right? 

New (restored) output:
screen shot 2015-11-25 at 9 34 35 am

**Comment by mathias** [comment]
Ok, now I know what's confusing about this message -- it should read that `MISSING_VAR is missing from the provision response`, not from `manifest`, right?

**Comment by mathias** [comment]
Better?
screen shot 2015-11-25 at 9 36 26 am

**Comment by bjeanes** [comment]
Yes. Empty or partial config provision responses is not an error. I think this is an improvement.

**Comment by bjeanes** [comment]
The inverse case of returning vars not in the manifest *is* an error, though, as I'm sure you're aware.

**Pull request merged**
