### PR TITLE
use creds from netrc

### PR DESCRIPTION
**Pull request by will**
```
kensa ➤ bundle exec bin/kensa pull securekey
Found credentials for will@heroku.com, proceed? (y/N) y
-----> Manifest for "securekey" received successfully
kensa ➤ rm addon-manifest.json
kensa ➤ bundle exec bin/kensa pull securekey                                                                                                                 git:master*
Found credentials for will@heroku.com, proceed? (y/N) n
Enter your Heroku Provider credentials.
Email:
Password:
```

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
+1.1

I generally don't approve of plus inflation, but I'm giving 110% here.

**Comment by bjeanes** [comment]
Merging because only 1.9.2 failed, which #81 removes.

**Comment by bjeanes** [comment]
@uhoh-itsmaciek @will new kensa version released with these changes. Thanks!

**Comment by uhoh-itsmaciek** [comment]
:joy:

**Comment by will** [comment]
yayyy

**Pull request merged**
