### PR TITLE
Update local manifest from server after push

### PR DESCRIPTION
**Pull request by bjeanes**
This lets Heroku return a normalised manifest on response to a new manifest version. Initially, this will be used to amend the `$revising` key which we will use to make sure all manifest pushes are based on the latest revision, which gives Heroku the opportunity to revise and normalise manifest formats.

attn @heroku/add-ons.

https://github.com/heroku/addons.heroku.com/pull/1060 to be merged and deployed after this is merged and released.

### CODE REVIEW

**Comment by mathias** [comment]
Wondering whether there's ever a case where we don't want it to have this behavior? I guess we can always add a flag later to disable this if it is necessary.

**Comment by bjeanes** [comment]
@mathias Hmm interesting... I can't think of one. As long as we always return a good manifest in the response to their push, I can't see a reason why we wouldn't be able to save it. If the push is rejected, an exception is raised and that code doesn't run.

**Comment by mathias** [comment]
I'm good with merging this, then. :+1:

**Comment by mattreduce** [comment]
Looks good to me, thanks @bjeanes!

**Pull request merged**
