### PR TITLE
Eliminate a source of much confusion: oauth token is the 'password'

### PR DESCRIPTION
**Pull request by mathias**

### CODE REVIEW

**Comment by mattreduce** [comment]
You can still use your password if you've not enabled two-factor auth, so this is only sometimes the case

**Comment by mathias** [comment]
Ah, that means that this is worse.

**Comment by mattreduce** [comment]
>Ah, that means that this is worse.

\\(^__^)/

**Comment by bjeanes** [comment]
Kensa pre-dates 2fa and 2fa adoption for our providers is low

**Pull request closed without merging**
